### ISSUE TITLE
Upgrade @ledgerhq/hw-transport

### ISSUE THREAD

**Issue by jorbuedo** [cardano-foundation/ledgerjs-hw-app-cardano#44]
@janmazak could you upgrade dependencies again like you did here https://github.com/cardano-foundation/ledgerjs-hw-app-cardano/commit/6b0cd76127f79a4e66845c3a829c09495172cb58 ?
There's new "europa" device and other changes that make types incompatible between latest `@ledgerhq/react-native-hid` and this library.

**Comment by janmazak** [comment]
I'm working on it.
https://github.com/vacuumlabs/ledgerjs-cardano-shelley/pull/212

**Comment by janmazak** [comment]
Should be done now. Please test with all the devices you support.
https://www.npmjs.com/package/@cardano-foundation/ledgerjs-hw-app-cardano/v/7.1.4

**Comment by jorbuedo** [comment]
Thanks @janmazak ! 
Is https://github.com/vacuumlabs/ledgerjs-cardano-shelley the new canonical repo for this package?
